apiVersion: v1
kind: Pod
metadata:
  name: web-sidecar
  labels: { app: web, tier: frontend }
spec:
  containers:
    - name: web                 # main container (serves on :8080)
      image: maziar/kubia:0.1
      ports: [{ containerPort: 8080 }]
    - name: sidecar             # sidecar
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
