apiVersion: apps/v1
kind: ReplicaSet
metadata: { name: web-rs }
spec:
  replicas: 3
  selector: { matchLabels: { app: web-rs } }
  template:
    metadata: { labels: { app: web-rs } }
    spec:
      containers:
        - name: kubia
          image: maziar/kubia:0.1
          ports: [{ containerPort: 8080 }]
